/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package view;

import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 *
 * @author hvp
 */
public class BookingDialog extends javax.swing.JDialog {

    /** Creates new form BookingDialog */
    public BookingDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        registerLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        eventDateTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        typeEventLabel = new javax.swing.JLabel();
        conferenceRadioButton = new javax.swing.JRadioButton();
        workdayRadioButton = new javax.swing.JRadioButton();
        banquetRadioButton = new javax.swing.JRadioButton();
        assistantsSpinner = new javax.swing.JSpinner();
        assistantsLabel = new javax.swing.JLabel();
        roomsLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        kitchenjComboBox = new javax.swing.JComboBox<>();
        roomsCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        registerLabel.setText("Register Fields");
        registerLabel.setToolTipText("Register Fields");

        nameLabel.setText("Name:");
        nameLabel.setToolTipText("Name");

        nameTextField.setToolTipText("Name");

        emailLabel.setText("E-mail:");
        emailLabel.setToolTipText("Email");

        emailTextField.setToolTipText("Email");
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        phoneLabel.setText("Phone Number:");
        phoneLabel.setToolTipText("Phone Number");

        dateLabel.setText("Event Date:");
        dateLabel.setToolTipText("Event Date");

        eventDateTextField.setToolTipText("Event Date");
        eventDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventDateTextFieldActionPerformed(evt);
            }
        });

        phoneTextField.setToolTipText("Phone Number");

        typeEventLabel.setText("Type of Event:");
        typeEventLabel.setToolTipText("Type of Event");

        buttonGroup1.add(conferenceRadioButton);
        conferenceRadioButton.setText("Conference");
        conferenceRadioButton.setToolTipText("Conference");
        conferenceRadioButton.setActionCommand("conference");

        buttonGroup1.add(workdayRadioButton);
        workdayRadioButton.setText("Workday");
        workdayRadioButton.setToolTipText("Workday");
        workdayRadioButton.setActionCommand("workday");

        buttonGroup1.add(banquetRadioButton);
        banquetRadioButton.setText("Banquet");
        banquetRadioButton.setToolTipText("Banquet");
        banquetRadioButton.setActionCommand("banquet");
        banquetRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banquetRadioButtonActionPerformed(evt);
            }
        });

        assistantsSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        assistantsSpinner.setToolTipText("Assistants");

        assistantsLabel.setText("Assistants:");
        assistantsLabel.setToolTipText("Assistants");

        roomsLabel.setText("Hotel rooms required?");
        roomsLabel.setToolTipText("Rooms required?");

        confirmButton.setText("Confirm");
        confirmButton.setToolTipText("Confirm");

        cancelButton.setText("Cancel");
        cancelButton.setToolTipText("Cancel");

        kitchenjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type Kitchen", "Buffet", "Menu", "Cook's Date", "No service" }));
        kitchenjComboBox.setToolTipText("Kitchen");

        roomsCheckBox.setToolTipText("Rooms required?");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerLabel)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(phoneLabel)
                                .addComponent(dateLabel))
                            .addGap(71, 71, 71)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneTextField)
                                .addComponent(eventDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailLabel)
                                .addComponent(nameLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(emailTextField))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(confirmButton))
                    .addComponent(kitchenjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(assistantsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeEventLabel)
                            .addComponent(conferenceRadioButton)
                            .addComponent(workdayRadioButton)
                            .addComponent(banquetRadioButton)
                            .addComponent(assistantsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(87, 87, 87))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(roomsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roomsCheckBox)
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(registerLabel)
                        .addGap(26, 26, 26)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(typeEventLabel)
                        .addGap(18, 18, 18)
                        .addComponent(banquetRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(workdayRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conferenceRadioButton)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel)
                            .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assistantsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assistantsLabel))))
                .addGap(14, 14, 14)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(eventDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomsLabel)
                            .addComponent(roomsCheckBox)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(kitchenjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(cancelButton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void eventDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eventDateTextFieldActionPerformed

    private void banquetRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banquetRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banquetRadioButtonActionPerformed

    public void addConfirmButtonActionListener(ActionListener al) {
        this.confirmButton.addActionListener(al);
    }
    
    public void addCancelButtonActionListener(ActionListener al) {
        this.cancelButton.addActionListener(al);
    }

    public String getEmailTextField() {
        return this.emailTextField.getText();
    }

    public String getEventDateTextField() {
        return this.eventDateTextField.getText();
    }

    public String getNameTextField() {
        return this.nameTextField.getText();
    }

    public String getPhoneTextField() {
        return this.phoneTextField.getText();
    }

    
    public String getSelectedOptions() {
        String option = null;
        if (buttonGroup1.getSelection() != null) {
            option = buttonGroup1.getSelection().getActionCommand();
        }
        return option;
    }
    
    public String getSelectedOptionCheckBox() {
        if (roomsCheckBox.isSelected()) {
            return "Yes";
        } else {
            return "No";
        }
    }
    
    public void addKitchenComboBoxItem(String item) {
        this.kitchenjComboBox.addItem(item);
    }
    
    public String getKitchenComboBoxItem() {
        return this.kitchenjComboBox.getSelectedItem().toString();
    }
    
    public int getSpinnerValue() {
        return (int) this.assistantsSpinner.getValue();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assistantsLabel;
    private javax.swing.JSpinner assistantsSpinner;
    private javax.swing.JRadioButton banquetRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton conferenceRadioButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField eventDateTextField;
    private javax.swing.JComboBox<String> kitchenjComboBox;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JCheckBox roomsCheckBox;
    private javax.swing.JLabel roomsLabel;
    private javax.swing.JLabel typeEventLabel;
    private javax.swing.JRadioButton workdayRadioButton;
    // End of variables declaration//GEN-END:variables

}
